app:
  addr : 127.0.0.1
  port: 8080
  debug: true
dataSource:
  host: 127.0.0.1
  database: smiling_blog
  user: root
  password: root
  port: 3306
  maxLifeTime: 120
  maxOpenConns: 10
  maxIdleConns: 5
redis:
  host: 127.0.0.1:6379
  password:
  db: 0
log:
  level: info
  path: .\runtime
  filename:  smiling